version: '2'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./www:/usr/share/nginx/html
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./conf/authnginx/htpasswd:/etc/nginx/authnginx/htpasswd
      - ./conf/myfirstpage.com:/etc/nginx/sites-available/myfirstpage.com
      - ./conf/mysecondpage.com:/etc/nginx/sites-available/mysecondpage.com
      - ./conf/mythirdpage.com:/etc/nginx/sites-available/mythirdpage.com
      - ./conf/hosts:/etc/hosts
